### ISSUE TITLE
"7+" is taking over

### ISSUE THREAD

**Issue by cjdenio** [sampoder/summer-streaks#4]
Maybe if it showed the streak number instead?

![image](https://user-images.githubusercontent.com/34525547/86152176-c71f4a00-bacd-11ea-8fc4-1b52fe2e22e6.png)

**Comment by sampoder** [comment]
@zachlatta thoughts?

**Comment by Muirrum** [comment]
I agree with this. I understand the reasoning behind doing it in the slack but I think on the scrapbook page it should display the actual number (and maybe the highest streak that the user kept?)

**Comment by zachlatta** [comment]
Hey all, I hear you but I think it's important that we keep shame out of the equation.

I don't want someone who has a big streak to miss their streak and then feel shame about restarting it.

I'm going to say we should keep 7+ for now, but open to reviewing and reconsidering in the coming weeks once the Scrapbook world is a bit more mature.

**Comment by sampoder** [comment]
@zachlatta thoughts on the max streak idea Matthew brought up?
